version: '3.0'
services:
  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 500M

  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: journeytunes_db
      MYSQL_USER: journeytunes_user
      MYSQL_PASSWORD: journeytunes_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-db:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 500M

  phpmyadmin-db:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
    ports:
      - "5050:80"
    deploy:
      resources:
        limits:
          memory: 500M

  discovery:
    build:
      context: ./discovery
      dockerfile: Dockerfile
    depends_on:
      - config-server
    ports:
      - "8761:8761"
    deploy:
      resources:
        limits:
          memory: 500M

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    depends_on:
      - discovery
      - config-server
      - mysql-db
      - phpmyadmin-db
    ports:
      - "8222:8222"
    deploy:
      resources:
        limits:
          memory: 500M

  spotify:
    build:
      context: ./spotify
      dockerfile: Dockerfile
    depends_on:
      - config-server
      - discovery
      - gateway
    deploy:
      resources:
        limits:
          memory: 500M

  users:
    build:
      context: ./user
      dockerfile: Dockerfile
    depends_on:
      - config-server
      - discovery
      - mysql-db
      - gateway
    deploy:
      resources:
        limits:
          memory: 500M

  emails:
    build:
      context: ./email
      dockerfile: Dockerfile
    depends_on:
      - config-server
      - discovery
      - mysql-db
      - gateway
    deploy:
      resources:
        limits:
          memory: 500M

  hotels:
    build:
      context: ./hotel
      dockerfile: Dockerfile
    depends_on:
      - config-server
      - discovery
      - mysql-db
      - gateway
    deploy:
      resources:
        limits:
          memory: 500M

  routes:
    build:
      context: ./routes
      dockerfile: Dockerfile
    depends_on:
      - config-server
      - discovery
      - mysql-db
      - gateway
    deploy:
      resources:
        limits:
          memory: 500M

  trips:
    build:
      context: ./trip
      dockerfile: Dockerfile
    depends_on:
      - config-server
      - discovery
      - mysql-db
      - gateway
    deploy:
      resources:
        limits:
          memory: 500M

  frontend:
    build:
      context: ./frontend-journeytunes
      dockerfile: Dockerfile
    ports:
      - "80:80"
    deploy:
      resources:
        limits:
          memory: 500M


volumes:
  mysql-db:
  frontend-vol:
