
spring:
  application:
    name: email
  config:
    import: optional:configserver:http://localhost:8888
  mail:
    host: smtp.gmail.com
    port: 587
    username: journeytunes3@gmail.com
    password: ahnokobgocciwqca
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true