eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: hotels
          uri : http://hotels:7000
          predicates:
            - Path=/hotels/api/v1/**
        - id: trips
          uri: http://trips:8000
          predicates:
            - Path=/trips/api/v1/**
        - id: users
          uri: http://users:9000
          predicates:
            - Path=/users/api/v1/**
        - id: spotify
          uri: http://spotify:6000
          predicates:
            - Path=/spotify/api/v1/**
        - id: email
          uri: http://emails:5000
          predicates:
            - Path=/emails/api/v1/**
        - id: routes
          uri: http://routes:4000
          predicates:
            - Path=/routes/api/v1/**
