eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka

server:
  port: 4000

spring:
  application:
    name: routes
springdoc:
  api-docs:
    path: /route-service/v3/api-docs #these urls will used to load the swagger ui of this service by the api gateway
  swagger-ui:
    path: /route-service/swagger-ui.html